name: prot_eval # trans_eval
channels:
  - defaults
  - bioconda
  - conda-forge
  - ostrokach-forge
  - esri
  - anaconda
dependencies:
  # - jupyterlab~=3.3.4
  - python=3.8
  - pandas~=1.3.5
  - biopython~=1.79
  - seaborn~=0.11.2
  - pip
  - scipy~=1.7.3
  - scikit-learn~=1.2.1
  - ete3~=3.1.2
  - pyqt~=5.9.2
  - fasta3~=36.3.8
  - hmmer
  - mafft
  - emboss
  - pytest
  - tqdm
  - pytest-datadir~=1.4.1
  - biotite
  - pytorch=1.13.1
  - transformers=4.17
  - datasets=1.18.3
  - cudatoolkit=11.7
  - iminuit<2
  - numba
  - numpy
  - pip:
      - sequence-models
      - fair-esm==0.4.2
      - "git+https://github.com/facebookresearch/esm.git@e5e7b06b9a093706607c229ab1c5c9821806814d" # ESM
      - -e .
      - torch-scatter -f https://data.pyg.org/whl/torch-1.13.1+cu117.html
      - torch-sparse -f https://data.pyg.org/whl/torch-1.13.1+cu117.html
      - torch-cluster -f https://data.pyg.org/whl/torch-1.13.1+cu117.html
      - torch-spline-conv -f https://data.pyg.org/whl/torch-1.13.1+cu117.html
      - torch-geometric
      - tmscoring